[[constraint]]
  name = "github.com/lithammer/shortuuid"
  version = "3.0.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/zserge/webview"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
